import { ReactComponent as ChevronDown } from "../assets/icons/chevron--down.svg";
import { Portrait } from "../components/ui/portrait";
import { Button } from "components/ui/button";
import { Section } from "components/ui/section";
import Head from "next/head";
import Image from "next/image";
import { useRef } from "react";

export default function Home() {
    const detailRef = useRef<HTMLDivElement>(null);

    const scrollToDetail = () => {
        detailRef.current?.scrollIntoView({ behavior: "smooth" });

        if (detailRef.current) {
            const top =
                detailRef.current?.getBoundingClientRect().top +
                window.pageYOffset -
                30;
            window.scrollTo({ top, behavior: "smooth" });
        }
    };

    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>

            <main>
                {/** Header */}
                <Section>
                    <div className='flex flex-1'>
                        <div className='flex-1 relative mt-auto'>
                            <Image
                                alt=''
                                src='/images/brazer.jpg'
                                width={902}
                                height={1094}
                            />
                        </div>
                    </div>

                    <div className='absolute top-0 left-0 w-screen flex flex-col items-center justify-center pt-12 bg-gradient-to-b from-slate-400'>
                        <h1 className='text-3xl uppercase pb-1 border-b-[1px]'>
                            Go Fourth
                        </h1>
                        <h2 className='text-xl pt-1'>1. Benedum-Trees Bldg</h2>
                    </div>

                    <div className='absolute bottom-0 left-0 w-screen flex flex-col items-center justify-center py-16 bg-gradient-to-t from-slate-300'>
                        <div className='flex'>
                            <Button>Play Audio</Button>
                            <Button>Look Inside</Button>
                        </div>

                        <div
                            tabIndex={0}
                            role='button'
                            className='flex flex-col mt-4 justify-center'
                            onClick={scrollToDetail}
                        >
                            <div>
                                <ChevronDown style={{ fill: "#fff" }} />
                            </div>
                            <div className='my-1 text-white'>Read More</div>
                        </div>
                    </div>
                </Section>

                {/** Detail */}
                <Section className='text-slate-600 h-auto' ref={detailRef}>
                    <div className='flex flex-col flex-1 bg-gradient-to-b from-slate-300'>
                        <div className='flex px-8 justify-center items-center'>
                            <Portrait subtitle='Mike Benedum'>
                                <Image
                                    alt=''
                                    src='/images/benedum.jpg'
                                    width={538}
                                    height={727}
                                />
                            </Portrait>

                            <Portrait subtitle='Joe Trees'>
                                <Image
                                    alt=''
                                    src='/images/trees.jpg'
                                    width={350}
                                    height={507}
                                />
                            </Portrait>
                        </div>

                        <div className='mt-4 text-center px-8'>
                            <p className='mt-2'>
                                Originally called the Machesney Building, this
                                19-story skyscraper of granite, brick, and
                                terracotta supported by 1,400 tons of structural
                                steel was built to appeal to stockbrokers and
                                bankers. Its lavish lobby is swathed in Italian
                                marble with bronze fixtures and coffered plaster
                                ceilings accented in gold leaf. Cutouts on both
                                sides ensured that if other skyscrapers were
                                built next door, the open shafts would still
                                admit light and air.
                            </p>
                            <p className='mt-4'>
                                The building was renamed in 1913 when it was
                                bought by two &quot;wildcatters&quot; who made
                                immense fortunes drilling for oil. From their
                                15h floor offices, Mike Benedum and Joe Trees
                                pioneered major oil discoveries in West
                                Virginia, Illinois, Louisiana, Arkansas, Texas,
                                and Mexico. Their long friendship was forged not
                                only in business but in suffering — each lost
                                his only son in 1918 during World War I.
                            </p>
                            <p className='mt-4'>
                                Both were generous philanthropists, Benedum
                                especially for his home state of West Virginia,
                                and Trees for his alma mater, the University of
                                Pittsburgh. The charitable foundation Mike and
                                Sarah Lantz Benedum established in memory of
                                their son, Claude Worthington Benedum, is still
                                in the building. A second charity here is the
                                Benter Foundation, founded by Bill Benter, who
                                has his offices on the uppermost floors.
                            </p>
                        </div>
                    </div>
                </Section>
            </main>
        </div>
    );
}
