import { ReactComponent as ChevronDown } from "../assets/icons/chevron--down.svg";
import { Button } from "components/ui/button";
import { Section } from "components/ui/section";
import Head from "next/head";
import Image from "next/image";

export default function Home() {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>

            <main>
                <Section>
                    <div className='flex flex-1'>
                        <div className='flex-1 relative mt-auto'>
                            <Image
                                alt=''
                                src='/images/brazer.jpg'
                                width={902}
                                height={1094}
                            />
                        </div>
                    </div>

                    <div className='absolute top-0 left-0 w-screen flex flex-col items-center justify-center pt-12 bg-gradient-to-b from-slate-400'>
                        <h1 className='text-3xl uppercase pb-1 border-b-[1px]'>
                            Go Fourth
                        </h1>
                        <h2 className='text-xl pt-1'>1. Benedum-Trees Bldg</h2>
                    </div>

                    <div className='absolute bottom-0 left-0 w-screen flex flex-col items-center justify-center py-16 bg-gradient-to-t from-slate-300'>
                        <div className='flex'>
                            <Button>Play Audio</Button>
                            <Button>Look Inside</Button>
                        </div>
                        <div className='mt-4'>
                            <ChevronDown style={{ fill: "#fff" }} />
                        </div>
                        <div className='my-1 text-white'>Read More</div>
                    </div>
                </Section>
            </main>
        </div>
    );
}
